name: Develop

on:
  push:
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true
          cache-dependency-path: go.sum

      - name: Build and test
        run: make test

      - name: Report test coverage
        uses: ncruces/go-coverage-report@v0
        with:
          report: true
          chart: true
          amend: true
        continue-on-error: true

  lint:
    runs-on: ubuntu-latest
    needs: build-and-test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true
          cache-dependency-path: go.sum

      - name: Lint Go code
        run: make lint

  scan:
    runs-on: ubuntu-latest
    needs: build-and-test
    permissions:
      security-events: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate SBOM
        uses: anchore/sbom-action@v0.20.4
        with:
          path: .
          format: spdx-json
          output-file: sbom.spdx.json

      - name: Scan SBOM with Grype
        id: scan
        uses: anchore/scan-action@v6
        with:
          sbom: sbom.spdx.json
          fail-build: true
          severity-cutoff: medium
          output-format: sarif

      - name: Upload SARIF report to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: ${{ steps.scan.outputs.sarif }}
          category: "SBOM Vulnerability Scan"
